/* eslint-disable @typescript-eslint/no-explicit-any */
// TODO Brainer!
const HTMLTagSingleElements = ["title"];

export const getSelectorsFromMetatag = async (metatag: string): Promise<any[]> => {
    const selectors: any[] = [];

    const RegexTag = new RegExp("^<([a-z]*?)(s.*?)?>", "gmi");
    const ResultTag = metatag.match(RegexTag);

    if (ResultTag !== null) {
        if (HTMLTagSingleElements.includes(ResultTag[0])) {
            const pattern = { selector: ResultTag[0] };
            selectors.push(pattern);
        }
    }

    return selectors;
};

export const METATAGS_SOURCE = {
    commun: ["<title>#titletext#</title>", '<meta charset="utf-8" />', '<meta name="viewport" content="#contenttext#" />'],
    url: [
        '<meta name="url" content="#contenttext#" />',
        '<meta name="og:url" content="#contenttext#" />',
        '<meta name="host" content="#contenttext#" />',
        '<link rel="index" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="self" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    referURL: [
        '<meta name="syndication-source" content="#contenttext#" />',
        '<meta name="original-source" content="#contenttext#" />',
        '<meta name="identifier-url" content="#contenttext#" />',
        '<meta name="linkage" content="#contenttext#" />',
        '<link rel="shortlink" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="canonical" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="archives" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="pingback" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="search" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="start" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="first" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="last" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="next" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="prev" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="previous" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    title: [
        '<meta name="title" content="#contenttext#" />',
        '<meta name="og:title" content="#contenttext#" />',
        '<meta name="dc.title" content="#contenttext#" />',
        '<meta name="subtitle" content="#contenttext#" />',
    ],
    name: [
        '<meta name="name" content="#contenttext#" />',
        '<meta name="og:site_name" content="#contenttext#" />',
        '<meta name="pagename" content="#contenttext#" />',
        '<meta name="application-name" content="#contenttext#" />',
    ],
    description: ['<meta name="description" content="#contenttext#" />', '<meta name="og:description" content="#contenttext#" />', '<meta name="dc.description" content="#contenttext#" />'],
    subject: [
        '<meta name="summary" content="#contenttext#" />',
        '<meta name="abstract" content="#contenttext#" />',
        '<meta name="subject" content="#contenttext#" />',
        '<meta name="dc.subject" content="#contenttext#" />',
    ],
    topic: [
        '<meta name="keywords" content="#contenttext#" />',
        '<meta name="topic" content="#contenttext#" />',
        '<meta name="page-topic" content="#contenttext#" />',
        '<meta name="note" content="#contenttext#" />',
    ],
    type: ['<meta name="page-type" content="#contenttext#" />', '<meta name="og:type" content="#contenttext#" />', '<meta name="medium" content="#contenttext#" />'],
    person: [
        '<meta name="author" content="#contenttext#" />',
        '<meta name="owner" content="#contenttext#" />',
        '<meta name="copyright" content="#contenttext#" />',
        '<meta name="dc.rights" content="#contenttext#" />',
        '<meta name="publisher" content="#contenttext#" />',
        '<meta name="dc.publisher" content="#contenttext#" />',
        '<meta name="profile:first_name" content="#contenttext#" />',
        '<meta name="profile:last_name" content="#contenttext#" />',
        '<meta name="dc.creator" content="#contenttext#" />',
        '<meta name="designer" content="#contenttext#" />',
        '<meta name="made" content="#contenttext#" />',
        '<meta name="contactName" content="#contenttext#" />',
        '<meta name="operator" content="#contenttext#" />',
        '<meta name="host-admin" content="#contenttext#" />',
        '<link rel="author" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="publisher" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="me" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    site: [
        '<meta name="directory" content="#contenttext#" />',
        '<meta name="audience" content="#contenttext#" />',
        '<meta name="category" content="#contenttext#" />',
        '<meta name="classification" content="#contenttext#" />',
        '<meta name="referrer" content="#contenttext#" />',
        '<meta name="target" content="#contenttext#" />',
        '<meta name="coverage" content="#contenttext#" />',
        '<meta name="distribution" content="#contenttext#" />',
        '<meta name="rating" content="#contenttext#" />',
        '<link rel="license" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="manifest" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    csrf: ['<meta name="csrf-param" content="#contenttext#" />', '<meta name="csrf-token" content="#contenttext#" />'],
    generator: [
        '<meta name="generator" content="#contenttext#" />',
        '<meta name="version" content="#contenttext#" />',
        '<meta name="id" content="#contenttext#" />',
        '<meta name="template" content="#contenttext#" />',
    ],
    dates: [
        '<meta name="date"content="#contenttext#" />',
        '<meta name="presdate" content="#contenttext#" />',
        '<meta name="search_date"content="#contenttext#" />',
        '<meta name="creation_date" content="#contenttext#" />',
        '<meta name="expires" content="#contenttext#" />',
        '<meta name="revised" content="#contenttext#" />',
        '<meta name="revisit-after" content="#contenttext#" />',
    ],
    robots: ['<meta name="robots" content="#contenttext#" />', '<meta name="googlebot" content="#contenttext#" />'],
    contact: [
        '<meta name="og:phone_number" content="#contenttext#" />',
        '<meta name="og:email" content="#contenttext#" />',
        '<meta name="reply-to" content="#contenttext#" />',
        '<meta name="og:fax_number" content="#contenttext#" />',
        '<meta name="contactPhoneNumber" content="#contenttext#" />',
        '<meta name="contactFaxNumber" content="#contenttext#" />',
        '<meta name="contactNetworkAddress" content="#contenttext#" />',
    ],
    language: ['<meta name="language" content="#contenttext#" />', '<meta name="content-language" content="#contenttext#" />', '<meta name="dc.language" content="#contenttext#" />'],
    localization: [
        '<meta name="og:street-address" content="#contenttext#" />',
        '<meta name="og:postal-code" content="#contenttext#" />',
        '<meta name="og:region" content="#contenttext#" />',
        '<meta name="og:locality" content="#contenttext#" />',
        '<meta name="og:country-name" content="#contenttext#" />',
        '<meta name="contactOrganization" content="#contenttext#" />',
        '<meta name="contactStreetAddress1" content="#contenttext#" />',
        '<meta name="contactZipcode" content="#contenttext#" />',
        '<meta name="contactCity" content="#contenttext#" />',
        '<meta name="contactCountry" content="#contenttext#" />',
        '<meta name="icbm" content="#contenttext#" />',
        '<meta name="geo.placename" content="#contenttext#" />',
        '<meta name="geo.position" content="#contenttext#" />',
        '<meta name="geo.region" content="#contenttext#" />',
        '<meta name="og:locale" content="#contenttext#" />',
        '<meta name="og:locale:alternate" content="#contenttext#" />',
        '<meta name="og:longitude" content="#contenttext#" />',
        '<meta name="og:latitude" content="#contenttext#" />',
        '<meta name="place:location:latitude" content="#contenttext#" />',
        '<meta name="place:location:longitude" content="#contenttext#" />',
    ],
    image: [
        '<meta name="image" content="#contenttext#" />',
        '<meta name="og:image" content="#contenttext#" />',
        '<meta name="og:image:alt" content="#contenttext#" />',
        '<meta name="og:image:type" content="#contenttext#" />',
        '<meta name="og:image:width" content="#contenttext#" />',
        '<meta name="og:image:height" content="#contenttext#" />',
        '<meta name="og:image:secure_url" content="#contenttext#" />',
    ],
    icon: [
        '<link rel="icon" href="#hreflink#" sizes="#size#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="fluid-icon" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="mask-icon" href="#hreflink#" color="#color#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="shortcut icon" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    audio: [
        '<meta name="og:audio" content="#contenttext#" />',
        '<meta name="og:audio:album" content="#contenttext#" />',
        '<meta name="og:audio:artist" content="#contenttext#" />',
        '<meta name="og:audio:title" content="#contenttext#" />',
        '<meta name="og:audio:type" content="#contenttext#" />',
        '<meta name="og:audio:secure_url" content="#contenttext#" />',
    ],
    video: [
        '<meta name="og:video" content="#contenttext#" />',
        '<meta name="og:video:type" content="#contenttext#" />',
        '<meta name="og:video:height" content="#contenttext#" />',
        '<meta name="og:video:width" content="#contenttext#" />',
        '<meta name="og:video:secure_url" content="#contenttext#" />',
        '<meta name="video:actor:id" content="#contenttext#" />',
    ],
    price: ['<meta name="og:price:amount" content="#contenttext#" />', '<meta name="og:price:currency" content="#contenttext#" />'],
    article: [
        '<meta name="article:author" content="#contenttext#" />',
        '<meta name="article:modified_time" content="#contenttext#" />',
        '<meta name="article:published_time" content="#contenttext#" />',
        '<meta name="article:section" content="#contenttext#" />',
        '<meta name="article:tag" content="#contenttext#" />',
    ],
    books: [
        '<meta name="books:author" content="#contenttext#" />',
        '<meta name="books:book" content="#contenttext#" />',
        '<meta name="books:canonical_name" content="#contenttext#" />',
        '<meta name="books:isbn" content="#contenttext#" />',
        '<meta name="books:official_site" content="#contenttext#" />',
        '<meta name="books:rating:scale" content="#contenttext#" />',
        '<meta name="books:rating:value" content="#contenttext#" />',
    ],
    points: ['<meta name="og:points" content="#contenttext#" />', '<meta name="game:points" content="#contenttext#" />'],
    music: [
        '<meta name="music:album:url" content="#contenttext#" />',
        '<meta name="music:creator" content="#contenttext#" />',
        '<meta name="music:musician" content="#contenttext#" />',
        '<meta name="music:song:url" content="#contenttext#" />',
    ],
    business: [
        '<meta name="business:contact_data:country_name" content="#contenttext#" />',
        '<meta name="business:contact_data:locality" content="#contenttext#" />',
        '<meta name="business:contact_data:postal_code" content="#contenttext#" />',
        '<meta name="business:contact_data:region" content="#contenttext#" />',
        '<meta name="business:contact_data:street_address" content="#contenttext#" />',
    ],
    restaurant: [
        '<meta name="restaurant:contact_info:country_name" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:email" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:locality" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:phone_number" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:postal_code" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:region" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:street_address" content="#contenttext#" />',
        '<meta name="restaurant:contact_info:website" content="#contenttext#" />',
        '<meta name="restaurant:menu" content="#contenttext#" />',
        '<meta name="restaurant:restaurant" content="#contenttext#" />',
        '<meta name="restaurant:section" content="#contenttext#" />',
        '<meta name="restaurant:variation:price:amount" content="#contenttext#" />',
        '<meta name="restaurant:variation:price:currency" content="#contenttext#" />',
    ],
    product: [
        '<meta name="product:availability" content="#contenttext#" />',
        '<meta name="product:condition" content="#contenttext#" />',
        '<meta name="product:price:amount" content="#contenttext#" />',
        '<meta name="product:price:currency" content="#contenttext#" />',
        '<meta name="product:retailer_item_id" content="#contenttext#" />',
    ],
    screen: [
        '<meta name="format-detection" content="#contenttext#" />',
        '<meta name="full-screen" content="#contenttext#" />',
        '<meta name="screen-orientation" content="#contenttext#" />',
        '<meta name="browsermode" content="#contenttext#" />',
        '<meta name="imagemode" content="#contenttext#" />',
        '<meta name="layoutmode" content="#contenttext#" />',
        '<meta name="nightmode" content="#contenttext#" />',
        '<meta name="x5-fullscreen" content="#contenttext#" />',
        '<meta name="x5-orientation" content="#contenttext#" />',
        '<meta name="x5-page-mode" content="#contenttext#" />',
        '<meta name="HandheldFriendly" content="#contenttext#" />',
        '<meta name="MobileOptimized" content="#contenttext#" />',
    ],
    dublinCore: [
        '<meta name="dc.format" scheme="dcterms.imt" content="#contenttext#" />',
        '<meta name="dc.type" scheme="dcterms.dcmitype" content="#contenttext#" />',
        '<meta name="dcterms.license" scheme="dcterms.uri" content="#contenttext#" />',
        '<meta name="dcterms.modified" scheme="dcterms.w3cdtf" content="#contenttext#" />',
        '<meta name="dcterms.rightsholder" content="#contenttext#" />',
        '<link rel="schema.dc" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="schema.dcterms" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    twitter: [
        '<meta name="twitter:app:country" content="#contenttext#" />',
        '<meta name="twitter:app:id:googleplay" content="#contenttext#" />',
        '<meta name="twitter:app:id:ipad" content="#contenttext#" />',
        '<meta name="twitter:app:id:iphone" content="#contenttext#" />',
        '<meta name="twitter:app:name:googleplay" content="#contenttext#" />',
        '<meta name="twitter:app:name:ipad" content="#contenttext#" />',
        '<meta name="twitter:app:name:iphone" content="#contenttext#" />',
        '<meta name="twitter:card" content="#contenttext#" />',
        '<meta name="twitter:creator" content="#contenttext#" />',
        '<meta name="twitter:data1" content="#contenttext#" />',
        '<meta name="twitter:data2" content="#contenttext#" />',
        '<meta name="twitter:description" content="#contenttext#" />',
        '<meta name="twitter:dnt" content="#contenttext#" />',
        '<meta name="twitter:image" content="#contenttext#" />',
        '<meta name="twitter:image:alt" content="#contenttext#" />',
        '<meta name="twitter:image:src" content="#contenttext#" />',
        '<meta name="twitter:label1" content="#contenttext#" />',
        '<meta name="twitter:label2" content="#contenttext#" />',
        '<meta name="twitter:player" content="#contenttext#" />',
        '<meta name="twitter:player:height" content="#contenttext#" />',
        '<meta name="twitter:player:width" content="#contenttext#" />',
        '<meta name="twitter:site" content="#contenttext#" />',
        '<meta name="twitter:title" content="#contenttext#" />',
        '<meta name="twitter:url" content="#contenttext#" />',
    ],
    apple: [
        '<meta name="apple-itunes-app" content="#contenttext#" />',
        '<meta name="apple-mobile-web-app-capable" content="#contenttext#" />',
        '<meta name="apple-mobile-web-app-status-bar-style" content="#contenttext#" />',
        '<meta name="apple-mobile-web-app-title" content="#contenttext#" />',
        '<meta name="apple-touch-fullscreen" content="#contenttext#" />',
        '<link rel="apple-touch-icon" href="#hreflink#" sizes="#size#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="apple-touch-startup-image" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    microsoft: [
        '<meta name="msapplication-config" content="#contenttext#" />',
        '<meta name="msapplication-navbutton-color" content="#contenttext#" />',
        '<meta name="msapplication-starturl" content="#contenttext#" />',
        '<meta name="msapplication-task" content="#contenttext#" />',
        '<meta name="msapplication-tooltip" content="#contenttext#" />',
        '<meta name="msapplication-window" content="#contenttext#" />',
        '<meta name="mssmarttagspreventparsing" content="#contenttext#" />',
        '<meta name="msvalidate.01" content="#contenttext#" />',
    ],
    facebook: ['<meta name="fb:admins" content="#contenttext#" />', '<meta name="fb:app_id" content="#contenttext#" />', '<meta name="fb:article_style" content="#contenttext#" />'],
    applink: [
        '<meta name="al:android:app_name" content="#contenttext#" />',
        '<meta name="al:android:package" content="#contenttext#" />',
        '<meta name="al:android:url" content="#contenttext#" />',
        '<meta name="al:ios" />',
        '<meta name="al:ios:app_name" content="#contenttext#" />',
        '<meta name="al:ios:app_store_id" content="#contenttext#" />',
        '<meta name="al:ios:url" content="#contenttext#" />',
        '<meta name="al:ipad:app_name" content="#contenttext#" />',
        '<meta name="al:ipad:app_store_id" content="#contenttext#" />',
        '<meta name="al:ipad:url" content="#contenttext#" />',
        '<meta name="al:iphone:app_name" content="#contenttext#" />',
        '<meta name="al:iphone:app_store_id" content="#contenttext#" />',
        '<meta name="al:iphone:url" content="#contenttext#" />',
        '<meta name="al:web:should_fallback" content="#contenttext#" />',
        '<meta name="al:web:url" content="#contenttext#" />',
    ],
    google: [
        '<meta name="google" content="#contenttext#" />',
        '<meta name="google-analytics" content="#contenttext#" />',
        '<meta name="google-play-app" content="#contenttext#" />',
        '<meta name="google-site-verification" content="#contenttext#" />',
        '<link rel="chrome-webstore-item" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
    pinterest: ['<meta name="pinterest" content="#contenttext#" description="#descriptiontext#" />', '<meta name="p:domain_verify" content="#contenttext#" />'],
    alexa: ['<meta name="alexaverifyid" content="#contenttext#" />'],
    skype: ['<meta name="skype_toolbar" content="#contenttext#" />'],
    norton: ['<meta name="norton-safeweb-site-verification" content="#contenttext#" />'],
    yandex: ['<meta name="yandex-verification" content="#contenttext#" />'],
    httpEquiv: [
        '<meta http-equiv="cache-control" content="#contenttext#" />',
        '<meta http-equiv="content-language" content="#contenttext#" />',
        '<meta http-equiv="content-security-policy" content="#contenttext#" />',
        '<meta http-equiv="content-type" content="#contenttext#" />',
        '<meta http-equiv="imagetoolbar" content="#contenttext#" />',
        '<meta http-equiv="expires" content="#contenttext#" />',
        '<meta http-equiv="page-enter" content="#contenttext#" />',
        '<meta http-equiv="page-exit" content="#contenttext#" />',
        '<meta http-equiv="pragma" content="#contenttext#" />',
        '<meta http-equiv="reply-to" content="#contenttext#" />',
        '<meta http-equiv="window-target" content="#contenttext#" />',
        '<meta http-equiv="x-dns-prefetch-control" content="#contenttext#" />',
        '<meta http-equiv="x-ua-compatible" content="#contenttext#" />',
    ],
    alternate: ['<link rel="alternate" href="#hreflink#" hreflang="#lang#" title="#hreftitle#" type="#mimetype#" />'],
    misc: [
        '<link rel="amphtml" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="dns-prefetch" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="edituri" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<meta name="blogcatalog" />',
        '<meta name="disqus" content="#contenttext#" />',
        '<meta name="microid" content="#contenttext#" />',
        '<meta name="mixpanel" content="#contenttext#" />',
        '<meta name="mobile-web-app-capable" content="#contenttext#" />',
        '<meta name="monetization" content="#contenttext#" />',
        '<meta name="theme-color" content="#contenttext#" />',
        '<meta name="tweetmeme-title" content="#contenttext#" />',
        '<meta name="uservoice" content="#contenttext#" />',
        '<meta name="wap-font-scale" content="#contenttext#" />',
        '<meta name="op:markup_version" content="#contenttext#" />',
        '<link rel="micropub" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="preconnect" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="prefetch" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="preload" href="#hreflink#" as="image" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="prerender" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
        '<link rel="webmention" href="#hreflink#" title="#hreftitle#" type="#mimetype#" />',
    ],
};
